title: Doctor Jekyll's GitHub Page Experiment
author: c0ff33-b34n
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first foray into GitHub Pages, following the GitHub
  Pages course from GitHub Learning Lab. I should have this
  completed before Mr Hyde arrives.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  c0ff33-b34n # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
